title: Paya Lebar Methodist Girls' School (Primary)
url: https://www.open.gov.sg
favicon: /images/Logo.png
colors:
  primary-color: "#f2bb16"
  secondary-color: "#d9043d"
  media-colors:
    - title: media-color-one
      color: "#2a0859"
    - title: media-color-two
      color: "#f29e38"
    - title: media-color-three
      color: "#8b572a"
    - title: media-color-four
      color: "#bd10e0"
    - title: media-color-five
      color: "#f2f2f2"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2d4vic2ex2d2h.amplifyapp.com
prod: https://master.d2d4vic2ex2d2h.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
